version: "3"

services:
  mongo:
    image: "bitnami/mongodb:4.4.4"
    env_file:
      - .env
    logging:
      driver: none
    volumes:
      - mongo:/bitnami/mongodb

  api:
    build:
      context: .
      dockerfile: ${PWD}/Dockerfile
    env_file:
      - .env
    command: yarn dev
    volumes:
      - .:/app/
    depends_on:
      - mongo
    ports:
      - 5000:${PORT}

volumes:
  mongo:
