name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Generate .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PORT: ${{ secrets.PORT }}
          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
          envkey_EMAIL: ${{ secrets.EMAIL }}
          envkey_EMAIL_USER: ${{ secrets.EMAIL_USER }}
          envkey_EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

          file_name: .env
          fail_on_empty: false

      - name: Build Docker images
        run: |
          docker build . -t pheivez-api:${{ github.sha }}

  run:
    runs-on: self-hosted

    needs:
      - build

    steps:
      - name: remove old container
        run: |
          docker rm --force pheivez-api

      - name: run new container
        run: |
          docker run -d --name pheivez-api -p 3000:3000 pheivez-api:${{ github.sha }}
