name: Run Test
on: [push]

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Report coverage
        run: echo 'Test Successfully Completed'
