name: Run Test
on: [push]

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test

      - name: Report coverage
        run: echo 'Test Successfully Completed'
